# Generated by Django 5.2.5 on 2025-08-10 11:09

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, validators=[api.validators.validate_non_empty_string])),
                ('dependencies', models.JSONField(validators=[api.validators.validate_dependencies])),
                ('module', models.CharField(max_length=255, validators=[api.validators.validate_non_empty_string])),
                ('objectName', models.CharField(max_length=255, validators=[api.validators.validate_non_empty_string])),
            ],
        ),
    ]
