# Generated by Django 5.2.5 on 2025-08-15 11:41

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobject',
            name='company',
            field=models.CharField(default='GenOne', max_length=255, validators=[api.validators.validate_non_empty_string]),
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='GenOne', max_length=255, validators=[api.validators.validate_non_empty_string])),
                ('tab', models.CharField(max_length=100)),
                ('field_id', models.CharField(max_length=100)),
                ('mandatory', models.BooleanField(default=False)),
                ('allowed_values', models.JSONField(blank=True, null=True)),
                ('sap_table', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_field_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_description', models.TextField(blank=True, null=True)),
                ('objectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='api.dataobject')),
            ],
        ),
    ]
