# Generated by Django 5.2.5 on 2025-08-15 11:46

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dataobject_company_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobject',
            name='module',
            field=models.CharField(max_length=255, unique=True, validators=[api.validators.validate_non_empty_string]),
        ),
        migrations.AlterField(
            model_name='dataobject',
            name='objectName',
            field=models.CharField(max_length=255, unique=True, validators=[api.validators.validate_non_empty_string]),
        ),
    ]
