# Generated by Django 5.2.5 on 2025-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dataobject_module_alter_dataobject_objectname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specs',
            options={'ordering': ['objectName__objectName', 'tab', 'position']},
        ),
        migrations.AddField(
            model_name='specs',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='specs',
            unique_together={('objectName', 'tab', 'field_id')},
        ),
    ]
