# Generated by Django 5.2.5 on 2025-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_specs_options_specs_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='mandatory',
            field=models.BooleanField(default='No'),
        ),
    ]
