# Generated by Django 5.2.5 on 2025-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_specs_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='mandatory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
