# Generated by Django 5.2.5 on 2025-08-20 15:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_specs_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobject',
            name='dependencies',
            field=models.JSONField(default=list, validators=[api.validators.validate_dependencies]),
        ),
    ]
