# Generated by Django 5.2.5 on 2025-08-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dataobject_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRuleTemplateUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=150, unique=True)),
                ('schema', models.JSONField()),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_rule_template_ui',
                'ordering': ['rule_name'],
            },
        ),
    ]
