# Generated by Django 5.2.5 on 2025-08-27 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customruletemplateui'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_applied', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_applied_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specs')),
            ],
        ),
    ]
