# Generated by Django 5.2.5 on 2025-08-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ruleapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleapplied',
            old_name='spec',
            new_name='spec_field_id',
        ),
    ]
