# Generated by Django 5.2.5 on 2025-08-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_spec_ruleapplied_spec_field_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleapplied',
            old_name='spec_field_id',
            new_name='spec',
        ),
    ]
