# Generated by Django 5.2.5 on 2025-08-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_spec_field_id_ruleapplied_spec'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ruleapplied',
            constraint=models.UniqueConstraint(fields=('spec', 'rule_applied', 'rule_applied_data'), name='unique_spec_rule_data'),
        ),
    ]
