# Generated by Django 5.2.5 on 2025-08-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ruleapplied_unique_spec_rule_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.dataobject')),
            ],
        ),
    ]
