# Generated by Django 5.2.5 on 2025-09-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_deletedfilerecord_filevalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='validation',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
