# Generated by Django 5.2.5 on 2025-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_datafile_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
