# Generated by Django 5.2.5 on 2025-09-06 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_datafile_validated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='api.dataobject')),
            ],
        ),
    ]
