# Generated by Django 5.2.5 on 2025-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_validationprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'WAITING FOR APPROVAL'), (1, 'APPROVED & READY FOR LOAD'), (2, 'REJECTED & RE-VALIDATE')], default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='approver_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
