# Generated by Django 5.2.5 on 2025-09-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_datafile_approval_status_datafile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='approval_link_used',
            field=models.BooleanField(default=False),
        ),
    ]
