# Generated by Django 5.2.5 on 2025-09-12 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_datafile_approval_link_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='approval_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='request_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='validation',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.datafile')),
            ],
        ),
    ]
