# Generated by Django 5.2.5 on 2025-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_datafile_approval_token_datafile_request_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcomment',
            name='action',
            field=models.CharField(choices=[('request_approval', 'Request Approval'), ('cancel_approval', 'Cancel Approval')], default='cancel_approval', max_length=50),
        ),
        migrations.AddField(
            model_name='approvalcomment',
            name='action_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='rejected', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
