# Generated by Django 5.2.5 on 2025-09-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_approvalcomment_action_approvalcomment_action_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalcomment',
            name='action',
            field=models.CharField(choices=[('request_approval', 'Request Approval'), ('cancel_approval', 'Cancel Approval')], max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalcomment',
            name='action_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
