# Generated by Django 5.2.5 on 2025-09-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_approvalcomment_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationprogress',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
