# Generated by Django 5.2.5 on 2025-09-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_validationprogress_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='data_load',
            field=models.IntegerField(default=0),
        ),
    ]
