# constants.py 
STATUS_FILE_PENDING = "FILE_PENDING" 
STATUS_UPLOAD_SUCCESS = "UPLOAD_SUCCESS" 
STATUS_VALIDATION_FAILED = "VALIDATION_FAILED" 
STATUS_VALIDATION_SUCCESS = "VALIDATION_SUCCESS" 
STATUS_LOAD_FAILED = "LOAD_FAILED" 
STATUS_LOAD_SUCCESS = "LOAD_SUCCESS" 
STATUS_LOAD_SUCCESS_WITH_ERRORS = "LOAD_SUCCESS_WITH_ERRORS"
